/**
 * Keep the MCP server launchable from a stable path.
 *
 * The MCP server used to be installed with `pipx install "zeroinfer[mcp]"`, which
 * put an `zeroinfer-mcp` command on PATH. There is no PyPI package any more, and
 * the two paths an MCP client would otherwise need - the app-managed venv and
 * the shipped `python/` tree inside the app bundle - are awkward: the second one
 * moves when the app is installed elsewhere or updated.
 *
 * So the app writes a tiny launcher into userData, which never moves, and
 * rewrites it on every boot so it always points at the current install:
 *
 *   claude mcp add zeroinfer -- <userData>/venv/.../python <userData>/zeroinfer-mcp.py
 *   codex  mcp add zeroinfer -- <userData>/venv/.../python <userData>/zeroinfer-mcp.py
 *
 * Every client runs that same stdio server and only disagrees about where the
 * registration is recorded (~/.claude.json, ~/.codex/config.toml, or Claude
 * Desktop's claude_desktop_config.json). Settings -> API & MCP prints the exact
 * command for each one.
 *
 * `mcp` and `httpx` are in the base venv (see python-env.SERVER_DEPS), so the
 * launcher has everything it needs.
 *
 * The MCP server is an HTTP *client* of ZeroInfer's local API - that is what lets
 * it reuse the models the app already has warm instead of loading a second
 * multi-GB copy of each one. The consequence is that **MCP only works while the
 * API is switched on** (Settings -> API server). With the API off there is
 * nothing for it to connect to, and it will say so.
 */
'use strict';

const fs = require('fs');
const path = require('path');

function launcherPath(userData) {
  return path.join(userData, 'zeroinfer-mcp.py');
}

/** (Re)write the launcher so it points at the current `python/` tree. */
function writeMcpLauncher(userData, pythonDir) {
  const body = `"""Generated by the ZeroInfer desktop app - do not edit.

Launches the ZeroInfer MCP server against the Python tree inside the currently
installed app. Rewritten on every launch, so it survives app updates.

    claude mcp add zeroinfer -- "${launcherPath(userData).replace(/\\/g, '\\\\')}"
    codex  mcp add zeroinfer -- "${launcherPath(userData).replace(/\\/g, '\\\\')}"
"""
import sys

sys.path.insert(0, r"${pythonDir}")

from mcp_server.server import main

if __name__ == "__main__":
    main()
`;
  try {
    fs.mkdirSync(userData, { recursive: true });
    fs.writeFileSync(launcherPath(userData), body, 'utf8');
    return launcherPath(userData);
  } catch {
    return null; // Non-fatal: MCP is optional, the app still runs without it.
  }
}

module.exports = { writeMcpLauncher, launcherPath };
